export type HttpMethod = 'DELETE' | 'GET' | 'POST' | 'PUT';

export type HttpEndpoint = {
  readonly method: HttpMethod;
  readonly path: string;
  readonly access: string;
  readonly description: string;
};

export type HttpApiGroup = {
  readonly number: string;
  readonly eyebrow: string;
  readonly title: string;
  readonly description: string;
  readonly endpoints: readonly HttpEndpoint[];
};

export const httpApiGroups: readonly HttpApiGroup[] = [
  {
    number: '01',
    eyebrow: 'Public surface',
    title: 'Discovery and content',
    description: 'Read the public publishing surface and inspect the live API contract.',
    endpoints: [
      {
        method: 'GET',
        path: '/',
        access: 'Public',
        description: 'Return the application greeting used by the health check.',
      },
      {
        method: 'GET',
        path: '/api/docs',
        access: 'Public',
        description: 'Open the interactive Swagger UI generated by NestJS.',
      },
      {
        method: 'GET',
        path: '/blogs',
        access: 'Public',
        description: 'Search and paginate published blogs.',
      },
      {
        method: 'GET',
        path: '/posts',
        access: 'Public',
        description: 'Search published posts with pagination and optional session context.',
      },
      {
        method: 'GET',
        path: '/posts/:postId/comments',
        access: 'Public',
        description: 'Read the paginated discussion attached to a post.',
      },
    ],
  },
  {
    number: '02',
    eyebrow: 'Identity',
    title: 'Sessions and account access',
    description: 'Create an account, establish a session, and manage token lifecycle.',
    endpoints: [
      {
        method: 'POST',
        path: '/auth/registration',
        access: 'Public',
        description: 'Register a user and start the email confirmation workflow.',
      },
      {
        method: 'POST',
        path: '/auth/login',
        access: 'Credentials',
        description: 'Exchange validated credentials for an access token and refresh cookie.',
      },
      {
        method: 'POST',
        path: '/auth/refresh-token',
        access: 'Refresh cookie',
        description: 'Rotate the session and issue a new access token.',
      },
      {
        method: 'GET',
        path: '/auth/me',
        access: 'Bearer token',
        description: 'Return the identity associated with the current access token.',
      },
      {
        method: 'POST',
        path: '/auth/logout',
        access: 'Refresh cookie',
        description: 'Revoke the active session and clear its refresh cookie.',
      },
    ],
  },
  {
    number: '03',
    eyebrow: 'Product workflows',
    title: 'Publishing and engagement',
    description: 'Create content and authenticated interactions on top of the public catalog.',
    endpoints: [
      {
        method: 'POST',
        path: '/posts',
        access: 'Bearer token',
        description: 'Create a post for a blog the current user can manage.',
      },
      {
        method: 'POST',
        path: '/posts/:postId/comments',
        access: 'Bearer token',
        description: 'Add a comment to an existing post.',
      },
      {
        method: 'PUT',
        path: '/posts/:postId/like-status',
        access: 'Bearer token',
        description: 'Update the current user reaction for a post.',
      },
      {
        method: 'POST',
        path: '/blogs/:blogId/subscription',
        access: 'Bearer token',
        description: 'Subscribe the current user to updates from a blog.',
      },
      {
        method: 'DELETE',
        path: '/blogs/:blogId/subscription',
        access: 'Bearer token',
        description: 'Remove the current user blog subscription.',
      },
    ],
  },
  {
    number: '04',
    eyebrow: 'Quiz and operations',
    title: 'Games and administration',
    description: 'Run the pair quiz and use protected administration endpoints.',
    endpoints: [
      {
        method: 'GET',
        path: '/pair-game-quiz/users/top',
        access: 'Public',
        description: 'Return the quiz leaderboard using the requested paging options.',
      },
      {
        method: 'POST',
        path: '/pair-game-quiz/pairs/connection',
        access: 'Bearer token',
        description: 'Match the current user and start or join a quiz pair.',
      },
      {
        method: 'POST',
        path: '/pair-game-quiz/pairs/my-current/answers',
        access: 'Bearer token',
        description: 'Submit an answer for the active quiz question.',
      },
      {
        method: 'GET',
        path: '/users',
        access: 'Basic auth',
        description: 'Search the protected user administration collection.',
      },
      {
        method: 'DELETE',
        path: '/users/:id',
        access: 'Basic auth',
        description: 'Remove a user through the administration boundary.',
      },
    ],
  },
] as const;
