export enum PaymentSystem {
  STRIPE = 'Stripe',
  PAYPAL = 'PayPal',
  SQUARE = 'Square',
  APPLE_PAY = 'Apple Pay',
  GOOGLE_PAY = 'Google Pay',
  AMAZON_PAY = 'Amazon Pay',
  VENMO = 'Venmo',
  BITCOIN = 'Bitcoin',
  MASTERPASS = 'Masterpass',
  VISA_CHECKOUT = 'Visa Checkout',
  AMERICAN_EXPRESS_CHECKOUT = 'American Express Checkout',
  ALIPAY = 'Alipay',
  WECHAT_PAY = 'WeChat Pay',
  KLARNA = 'Klarna',
  AFTERPAY = 'Afterpay',
  SEZZLE = 'Sezzle',
  AFFIRM = 'Affirm',
  SHOP_PAY = 'Shop Pay',
}
