export enum EndpointKeys {
  Me = 'Me',
  Users = 'Users',
  Auth = 'Auth',
  SA = 'SA',
  Blogger = 'Blogger',
  Blogs = 'Blogs',
  Posts = 'Posts',
  Comments = 'Comments',
  Mails = 'Mails',
  SecurityDevices = 'SecurityDevices',
  Testing = 'Testing',
  SaQuizQuestions = 'SaQuizQuestions',
  PairGameQuiz = 'PairGameQuiz',
  Telegram = 'Telegram',
  Payment = 'Payment',
  Products = 'Products',
  Stripe = 'Stripe',
  PayPal = 'PayPal',
}
