export type PgKeysType =
  | 'PG_LOCAL_DATABASE'
  | 'PG_HEROKU_NAME_DATABASE'
  | 'PG_URI_LOCAL'
  | 'PG_HOST_HEROKU'
  | 'PG_DOMAIN_HEROKU'
  | 'DATABASE_URL'
  | 'PG_HEROKU_USER_NAME'
  | 'PG_HEROKU_USER_PASSWORD'
  | 'PG_LOCAL_USER_NAME'
  | 'PG_LOCAL_USER_PASSWORD';
