name: Test & Deploy #The name of the pipeline that will perform GitHub actions

on:
  push:
    branches:
      - staging # specify the name of the branch in which we want to push and launch our deployment


jobs:
  tests:
    name: Tests # the name of a specific job in pipeline !!!
    runs-on: ubuntu-latest
    steps:
      - name: Checkout  # cloning the repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn # installing dependencies

      - name: Test
        run: yarn test:e2e # run the script with tests
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          ACCESS_SECRET_KEY: ${{ secrets.ACCESS_SECRET_KEY }}
          ATLAS_URI: ${{ secrets.ATLAS_URI }}
          BASIC_AUTH: ${{ secrets.BASIC_AUTH }}
          DEV_DATABASE: ${{ secrets.DEV_DATABASE }}
          EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
          EXP_ACC_TIME: ${{ secrets.EXP_ACC_TIME }}
          EXP_REF_TIME: ${{ secrets.EXP_REF_TIME }}
          MAIL_HOST: ${{ secrets.MAIL_HOST }}
          NODEMAILER_APP_PASSWORD: ${{ secrets.NODEMAILER_APP_PASSWORD }}
          NODEMAILER_EMAIL: ${{ secrets.NODEMAILER_EMAIL }}
          PROD_NEST_DATABASE: ${{ secrets.PROD_NEST_DATABASE }}
          REFRESH_SECRET_KEY: ${{ secrets.REFRESH_SECRET_KEY }}
          TEST_DATABASE: ${{ secrets.TEST_DATABASE }}
          THROTTLE_LIMIT: ${{ secrets.THROTTLE_LIMIT }}
          THROTTLE_TTL: ${{ secrets.THROTTLE_TTL }}

  Sync-main-branch:
    name: Sync-main-branch
    runs-on: ubuntu-latest
    needs: Tests
    steps:
      - uses: actions/checkout@master
      - name: Merge staging -> main
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: staging
          target_branch: main
          github_token: ${{ github.token }}